### ISSUE TITLE
FutureWarning

### ISSUE THREAD

**Issue by noamsgl** [NiZiL/esnpy#1]
When running the `trajectories.py` example, I get the following warning:

FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

https://github.com/NiziL/esnpy/blob/02b7a7f028d0ee5147e1620588355d3f4fdf42b5/esnpy/core.py#L25

**Comment by NiziL** [comment]
Thank you !
