### ISSUE TITLE
Trouble running on data with multiple dimensions

### ISSUE THREAD

**Issue by noamsgl** [NiZiL/esnpy#3]
Hello

I'm trying to run `esnpy` with my own data.

My data is given in the form X (a numpy array of shape (19000, 342)) and y (a numpy array of shape (19000, 1)) where X is the signal and y is the target.

I've tried running your examples but I run into problems because the dimensions are not exactly the same as yours.

Any help would be appreciated. Thanks in advance  🙏

**Comment by NiziL** [comment]
@noamsgl I'm so sorry, answering so late... It's been a really long time since I've play around this lib, did you manage to get it work ?
